// <auto-generated />
using System;
using EInvoiceAndEReceipt.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EInvoiceAndEReceipt.Data.Migrations
{
    [DbContext(typeof(EInvoiceDbContext))]
    [Migration("20251117111001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Delievry", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<string>("Approach")
                        .HasColumnType("text");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("text");

                    b.Property<string>("DateValidity")
                        .HasColumnType("text");

                    b.Property<string>("ExportPort")
                        .HasColumnType("text");

                    b.Property<decimal?>("GrossWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("Packaging")
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.ToTable("Delievries");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Discount", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.HasKey("_Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<DateTime>("DateTimeIssued")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Delievry_Id")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentTypeVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExtraDiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Issuer_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("Payment_Id")
                        .HasColumnType("integer");

                    b.Property<string>("ProformaInvoiceNumber")
                        .HasColumnType("text");

                    b.Property<string>("PurchaseOrderDescription")
                        .HasColumnType("text");

                    b.Property<string>("PurchaseOrderReference")
                        .HasColumnType("text");

                    b.Property<int>("Receiver_Id")
                        .HasColumnType("integer");

                    b.Property<string>("SalesOrderDescription")
                        .HasColumnType("text");

                    b.Property<string>("SalesOrderReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ServiceDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxpayerActivityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalItemsDiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("numeric");

                    b.HasKey("_Id");

                    b.HasIndex("Delievry_Id");

                    b.HasIndex("Issuer_Id");

                    b.HasIndex("Payment_Id");

                    b.HasIndex("Receiver_Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.InvoiceLine", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Discount_Id")
                        .HasColumnType("integer");

                    b.Property<string>("InternalCode")
                        .HasColumnType("text");

                    b.Property<int?>("Invoice_Id")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ItemsDiscount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalesTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalTaxableFees")
                        .HasColumnType("numeric");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitValue_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValueDifference")
                        .HasColumnType("numeric");

                    b.HasKey("_Id");

                    b.HasIndex("Discount_Id");

                    b.HasIndex("Invoice_Id");

                    b.HasIndex("UnitValue_Id");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Issuer", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<int>("Address_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.HasIndex("Address_Id");

                    b.ToTable("Issuers");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.IssuerAddress", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Floor")
                        .HasColumnType("text");

                    b.Property<string>("Governate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LandMark")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("RegionCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.ToTable("IssuerAddresses");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Payment", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<string>("BankAccountIBAN")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountNo")
                        .HasColumnType("text");

                    b.Property<string>("BankAddress")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Receiver", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<int>("Address_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.HasIndex("Address_Id");

                    b.ToTable("Receivers");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.ReceiverAddress", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Floor")
                        .HasColumnType("text");

                    b.Property<string>("Governate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LandMark")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("RegionCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.ToTable("ReceiverAddresses");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Signature", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<int?>("Invoice_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.HasIndex("Invoice_Id");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.TaxTotal", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("Invoice_Id")
                        .HasColumnType("integer");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.HasIndex("Invoice_Id");

                    b.ToTable("TaxTotals");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.TaxableItem", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("InvoiceLine_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.HasIndex("InvoiceLine_Id");

                    b.ToTable("TaxableItems");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Value", b =>
                {
                    b.Property<int>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_Id"));

                    b.Property<decimal>("AmountEGP")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountSold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrencyExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<string>("CurrencySold")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("_Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Invoice", b =>
                {
                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Delievry", "Delievry")
                        .WithMany()
                        .HasForeignKey("Delievry_Id");

                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Issuer", "Issuer")
                        .WithMany()
                        .HasForeignKey("Issuer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("Payment_Id");

                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Receiver", "Receiver")
                        .WithMany()
                        .HasForeignKey("Receiver_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delievry");

                    b.Navigation("Issuer");

                    b.Navigation("Payment");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.InvoiceLine", b =>
                {
                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("Discount_Id");

                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Invoice", null)
                        .WithMany("InvoiceLines")
                        .HasForeignKey("Invoice_Id");

                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Value", "UnitValue")
                        .WithMany()
                        .HasForeignKey("UnitValue_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("UnitValue");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Issuer", b =>
                {
                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.IssuerAddress", "Address")
                        .WithMany()
                        .HasForeignKey("Address_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Receiver", b =>
                {
                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.IssuerAddress", "Address")
                        .WithMany()
                        .HasForeignKey("Address_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Signature", b =>
                {
                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Invoice", null)
                        .WithMany("Signatures")
                        .HasForeignKey("Invoice_Id");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.TaxTotal", b =>
                {
                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Invoice", null)
                        .WithMany("TaxTotals")
                        .HasForeignKey("Invoice_Id");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.TaxableItem", b =>
                {
                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.InvoiceLine", null)
                        .WithMany("TaxableItems")
                        .HasForeignKey("InvoiceLine_Id");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.User", b =>
                {
                    b.HasOne("EInvoiceAndEReceipt.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceLines");

                    b.Navigation("Signatures");

                    b.Navigation("TaxTotals");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.InvoiceLine", b =>
                {
                    b.Navigation("TaxableItems");
                });

            modelBuilder.Entity("EInvoiceAndEReceipt.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
